### ISSUE TITLE
"Try-it-here" example points to the wrong API

### ISSUE THREAD

**Issue by asdasdsadasdas** [AirReps/website-content#15]
Chipset API example points to the Discord API:

https://docs.airreps.info/docs/api-chipset#example --> https://apitester.com/shared/checks/b72c43219c0b4448ae3a4fd134025031

**Comment by wavpro** [comment]
The link is correct, closing issue.

**Comment by wavpro** [comment]
Will update website. Thanks for bringing this issue up.
