### ISSUE TITLE
Equalisers showing up twice in sidebar.

### ISSUE THREAD

**Issue by wavpro** [AirReps/website-content#18]
![Screenshot 2021-03-08 at 10 16 57](https://user-images.githubusercontent.com/31097540/110300807-a366b900-7ff7-11eb-8afa-cb47048e42b7.png)

**Comment by asdasdsadasdas** [comment]
D'oh!

**Comment by asdasdsadasdas** [comment]
Fixed with commit in airreps-site repo: 
https://github.com/AirReps/airreps-site/commit/3a97bc21bd291c6bef8a4f611e0aa7a40983f41f
